### ISSUE TITLE
@farmfe/plugin-react - configure development mode a bit more

### ISSUE THREAD

**Issue by chneau** [farm-fe/plugins#80]
Hello,

I am using https://chromewebstore.google.com/detail/locatorjs/npbfdllefekhdplbkdigpncggmojpefi and this is pretty awesome to click on component and see code on VSCode straight away.

To do so I enable `development: true` in the react plugin like so:
![image](https://github.com/user-attachments/assets/569a07b3-6a37-415d-994b-786d18550c4c)
I noticed it enabled these plugins:
![image](https://github.com/user-attachments/assets/ba5200b9-d065-4c2b-b5b8-1c32d2031a44)

And there I am interested to know how to configure `@swc/plugin-transform-react-jsx-source` ?

I was wondering if there is a way for the development mode to set the full path of the source file instead of relative?

That would make the configuration string to open vscode slightly simpler, for now mine is like this:

vscode://vscode-remote/ssh-remote+ncce/home/c/go/src/github.com/celerumltd/TLS-v4-frontend/${projectPath}${filePath}:${line}:${column}

and I wish it to be like that if it was possible to enable full path instead of relative path:

vscode://vscode-remote/ssh-remote+ncce/${projectPath}${filePath}:${line}:${column}

**Comment by wre232114** [comment]
`@swc/plugin-transform-react-jsx-source` can not be configured and I'll add a option support configuring the file path to absolute path

**Comment by wre232114** [comment]
@chneau Try `@farmfe/plugin-react@1.2.3`, I added a option named `useAbsolutePath`, set it to true then the generated file path would be absolute

**Comment by chneau** [comment]
@wre232114 Hello and thanks for tghe quick reply! 

Unfortunately I get this error at the moment:

```bash
[ building ] ⠂ transform (13) node_modules/react-refresh/runtime.js                                                                                                                                                                                            thread '<unnamed>' panicked at crates/node/src/plugin_toolkit/swc_transforms.rs:26:88:
called `Result::unwrap()` on an `Err` value: Error("unknown field `useAbsolutePath`, expected one of `runtime`, `importSource`, `pragma`, `pragmaFrag`, `throwIfNamespace`, `development`, `useBuiltIns`, `useBuiltins`, `useSpread`, `refresh`", line: 1, column: 37)
stack backtrace:
[ building ] ⠂ transform (17) node_modules/@farmfe/runtime-plugin-hmr/src/types.ts.farm-runtime                                                                                                                                                                note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm using the latest versions:

```json
		"@farmfe/cli": "^1.0.4",
		"@farmfe/core": "^1.3.27",
		"@farmfe/plugin-react": "^1.2.3",
		"@farmfe/plugin-sass": "^1.1.0",
```

**Comment by wre232114** [comment]
I'll fix it now

**Comment by wre232114** [comment]
try `@farmfe/plugin-react@1.2.4`, I tried localtorjs working fine

**Comment by chneau** [comment]
Thank you so much :) that works perfectly! cheers!
